### ISSUE TITLE
This if statement doesn't seem to do anything, safe to remove?

### ISSUE THREAD

**Issue by Kirkkt** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#100]
git blame goes to @dmitrig01 

https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/master/src/0_storage.js#L18

**Comment by dmitrig01** [comment]
this one?
```
if (TITANIUM_BUILD) {
	/** @typedef {{listProperties: function(), setString: function({string}, {string}), getString: function({string})}}*/
	Ti.App.Properties;
}
```

**Comment by Kirkkt** [comment]
Yes. Just a cautionary check in case we missed some logic. :)

**Comment by dmitrig01** [comment]
Well, this doesn't belong in this file (it belongs in externs), but it is important: https://developers.google.com/closure/compiler/docs/api-tutorial3#externs

(it's really worth reading the entire "Advanced Topics" section of the closure compiler docs)

**Comment by Kirkkt** [comment]
Cool. Thanks for the info. I will investigate the possibility of either:

1, rewrite this so that it doesn't trigger the lint.sh warning
2, add a jshint comment to suppress the said warning.

Thanks very much, @dmitrig01 !
