### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by navasiloy** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#106]
TypeError: undefined is not an object (evaluating 'e.identity_id.toString')
on https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/master/dist/build.js#L1497

c.identity_id = e.identity_id.toString();

This could be changed to:
c.identity_id = (e.identity_id ? e.identity_id.toString() : undefined);

**Comment by Kirkkt** [comment]
Thanks @navasiloy for raising the issue!

It is a bug indeed and I just sent out a fix following your suggestion. I also added a test to prevent the same from happening in the future.

https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/compare/kirk-fixnpe

:)

**Comment by Kirkkt** [comment]
Fixed with https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/pull/107

**Comment by navasiloy** [comment]
Great!
Thanks for fast reaction :)
