### ISSUE TITLE
No new link created if already exists, even if link data has changed

### ISSUE THREAD

**Issue by aaustin** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#108]
```js
(function(b,r,a,n,c,h,_,s,d,k){if(!b[n]||!b[n]._q){for(;s<_.length;)c(h,_[s++]);d=r.createElement(a);d.async=1;d.src="https://cdn.branch.io/branch-v1.6.6.min.js";k=r.getElementsByTagName(a)[0];k.parentNode.insertBefore(d,k);b[n]=h}})(window,document,"script","branch",function(b,r){b[r]=function(){b._q.push([r,arguments])}},{_q:[],_v:1},"init data first addListener removeListener setIdentity logout track link sendSMS referrals credits creditHistory applyCode validateCode getCode redeem banner closeBanner".split(" "), 0);


branch.init('key');
var linkData = {
    data: { "test": "1" }
};
console.log(linkData);
branch.sendSMS("your number", linkData, {}, callback);
```

Then change link data

```js
branch.init('key');
var linkData = {
    data: { "test": "2" }
};
console.log(linkData);
branch.sendSMS("your number", linkData, {}, callback);
```

It will text the same link from "test":"1"

**Comment by Kirkkt** [comment]
Sorry, I must've closed by accident

**Comment by Kirkkt** [comment]
@aaustin 

There is an boolean option called `make_new_link`, and setting it to be `true`, `false` or leave it blank (which reads `undefined` and it's the same as `false`) leads to different behaviors:

1. if `make_new_link` is true.
We will make a new link every time branch.sendSMS() is called

2. if `make_new_link` is false.
We will reuse the link, if it exists. 

As for this issue, the same link with a different linkData is considered the same link, this is important for us to pass on the original referral information. If there is a need for overwriting existing links with new linkData, setting `make_new_link` to be true will suffice.

Let me know if this makes sense. :)

link to the doc of branch.sendSMS(): https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/blob/master/WEB_GUIDE.md#sendsmsphone-linkdata-options-callback

**Comment by aaustin** [comment]
I think what we want to do here is differentiate between the 'referring link' and the 'previously passed in' link. It's normal behavior for the referring link to overwrite what's passed in. It's odd behavior that the previously used link in the sendSMS call would overwrite it. Does that make sense?

**Comment by Kirkkt** [comment]
@aaustin fixed with https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/pull/143

Many thanks for raising the issue!
