### ISSUE TITLE
10% of requests does not receive deeplink data

### ISSUE THREAD

**Issue by navasiloy** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#127]
10% of branch init calls does not receive deeplink info

Here are the the screenshot I've prepred:
1. https://www.dropbox.com/s/gjvke20amnyaqn0/link.png?dl=0  - generated link (including deep link data)
2. https://www.dropbox.com/s/wzq9bc2zd8xb2c8/code.png?dl=0 - the code I run during initial page load (including console logs)
3. https://www.dropbox.com/s/avukzw71uzuf1bk/success.png?dl=0 - the successful getting deep linking data (including console logs)
4. https://www.dropbox.com/s/trkir8e94g1a0qo/fail.png?dl=0 - getting deep linking data failing (including console logs)
5. https://www.dropbox.com/s/gpyyqnwxsp74dpr/fail-network.png?dl=0 - networktab (with location header redirect)
6. https://www.dropbox.com/s/gbm40cidsu9hxmv/success-network.png?dl=0 - networktab (with location header redirect) 

I'm happy to provide our environment for testing
The requests are running into incognito tab on chrome

**Comment by navasiloy** [comment]
Here is a small movie where you can see how it can be reproduced
https://www.dropbox.com/s/ztnfb2ikin4kwal/video.mkv?dl=0

**Comment by Kirkkt** [comment]
Thank you so much for raising the issue. I'm on it.

**Comment by Kirkkt** [comment]
@navasiloy 
This could be an issue in which the backend failed to lookup the deeplink info.

We can check against the backend error log to get a clue. 10% fail rate is unacceptably high had the backend not been in a rough state.

Looking at the screencase it has a clock in it, may I check with you the clock is reliable, and may I know your timezone?

Thank you in advance!

**Comment by navasiloy** [comment]
sure, I'm on EEST timezone
skype: navasiloy

**Comment by Kirkkt** [comment]
Hi @navasiloy ,

This issue is hard to pin down deterministically. I would recommend that you talk to our support team, who would probably be better suited to help.

I would also recommend that you run the scenario again so that we have something recent to refer to. If the same error occurs, feel free to send an email to support@branch.io . When you do, make sure to include the branch key used and time of failure.

Thank you!

**Comment by derrickstaten** [comment]
@navasiloy I'm on the support team. Please drop us a note with the branch key, time of failure and link used, like @Kirkkt indicated. It's easiest for us to investigate cases that are less than 24 hours old, so if it's not too much work, please try clicking until you recreate the issue again.

We're also investigating this on our side. There are two related issues, one inherent with fingerprinting, and one a bug that we see well < 1% of the time and are close to isolating and fixing. With the three data points requested above we can dig in and tell you definitively what is happening. Looking forward to your email.
