### ISSUE TITLE
Linker warnings in Xcode 7 / iOS 9 SDK — built for newer iOS version (8.3) than being linked (7.0) 

### ISSUE THREAD

**Issue by Vishal-0057** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#178]
Hello Team,

I am getting following warnings while compiling.

ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCEncodingUtils.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCServerResponse.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCError.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCSystemObserver.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(Branch.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BranchServerInterface.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCLinkData.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCPreferenceHelper.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BranchActivityItemProvider.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCServerRequestQueue.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCLinkCache.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCServerInterface.o)) was built for newer iOS version (8.3) than being linked (7.0)
ld: warning: object file (/Users/abhayam/Documents/famelive-iphone-app/Branch.framework/Branch(BNCServerRequest.o)) was built for newer iOS version (8.3) than being linked (7.0)

**Comment by aaustin** [comment]
Hi @Vishal-0057 - we've migrated the Cordova/Ionic SDK to a separate repository: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK and: https://www.npmjs.com/package/branch-cordova-sdk This should be resolved.
