### ISSUE TITLE
Cordova/Ionic Unable to Install

### ISSUE THREAD

**Issue by hookano** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#196]
Fails with error:

Failed to install 'io.branch.sdk':Error: ENOENT, no such file or directory '<snip>/io.branch.sdk/dist/cordova/build.js'

Looks like plugin.xml is pointing to dist/cordova/build.js - but the file is dist/build.js

**Comment by aaustin** [comment]
Hi @hookano - we've migrated the Cordova/Ionic SDK to a separate repository: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK and: https://www.npmjs.com/package/branch-cordova-sdk This should be resolved.
