### ISSUE TITLE
SDK breaks when sessionStorage/localStorage are disabled

### ISSUE THREAD

**Issue by elsbree** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#210]
When I disable localStorage and sessionStorage in Chrome (Settings Tab-> Advanced -> Content Settings -> Block sites from setting any data), the SDK triggers a security error. A similar error will happen in any browser with localStorage disabled. For example, when I open the example page linked in the readme, I see this message:

![image](https://cloud.githubusercontent.com/assets/521560/10464389/6c473f70-719e-11e5-9e58-af97921334d4.png)

This could be solved by using a `utils.localStorage` object that is set to window.localStorage when allowed, and uses a polyfill when not allowed. I'd be happy to submit a PR.

**Comment by mrubens** [comment]
I'm also running into this issue, causing the entire webpage to fail to load for users with cookies disabled. Any timeline for a fix? Thanks!

**Comment by elsbree** [comment]
I have a fork which fixes the issue here: https://github.com/ToneDen/Smart-App-Banner-Deep-Linking-Web-SDK. Not currently up-to-date with the upstream, though.

**Comment by jsaleigh** [comment]
@elsbree Awesome, thanks for that! We've been going back through to clean up a few items like this, but haven't gotten to this one yet. I know it's a bit late, but are you still willing to put in a PR?

**Comment by elsbree** [comment]
Just submitted a PR.

**Comment by jsaleigh** [comment]
@elsbree Thanks again! I've made a few modifications and merged a different branch into the master branch.  We should have an official deployment soon, with a tagged version.  Hopefully this will be useful to you, please let me know if you have any issues with it.

**Comment by elsbree** [comment]
Awesome, thanks!

**Comment by turadg** [comment]
@jsaleigh can you cut a release with this fix? it's a prod bug for us.

**Comment by jsaleigh** [comment]
@turadg Sorry for delay, the team just pushed out v1.8.2 with this fix: https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/tree/v1.8.2

**Comment by dmitrig01** [comment]
going to close this. feel free to reopen or make a new issue if it doesn't solve it

**Comment by turadg** [comment]
Thanks, working now for us.

**Comment by lwhuybrechts** [comment]
I was also running into this issue on v1.8.1. I just updated to v1.8.2 and the problem seems solved when I disable cookies in chrome, but when i disable ONLY the local storage it still crashes.

This can be reproduced bij adding --disable-local-storage to the target field of a Chrome shortcut. Every pageload I get the following crash in the branch sdk: "Cannot read property 'setItem' of null".
Any ideas?
