### ISSUE TITLE
forgetHide option doesn't work as expected

### ISSUE THREAD

**Issue by mdoyle13** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#234]
I have changed the forgetHide option to an integer of 3. After I visit the page, close the banner, close the browser tab and re open the page - the banner shows up again. I can't see any evidence of a cookie being set either. 

UPDATE:

I just updated the sdk from 1.6.1 to 1.7.1 and am still experiencing the same issue.

**Comment by Mojo90** [comment]
Same for me. I made a "quick and dirty" workaround, which works for me right now. I'd like to have a forgetHide after 14 days. Here is the code. If you just want a forget without popping up after X days just set a true or false value in local storage and if this is setted dont show banner - works till this is fixed in SDK 😎

```
var showBanner = localStorage.getItem("showBranchBannerAfterDays");
var checkDays = 14;
if(showBanner != null){
    var date = new Date(JSON.parse(showBanner));
    var today = new Date();
    var timeDiff = Math.abs(today.getTime() - date.getTime());
    checkDays = Math.ceil(timeDiff / (1000 * 3600 * 24)); 
}
if(checkDays > 13){
    branch.init('key_live_XXX');

    // Specify an event to listen for
    branch.addListener('willCloseBanner', function(){
        localStorage.setItem("showBranchBannerAfterDays", JSON.stringify(new Date()));
    });

    branch.banner({
        <--Banner configuration-->
    }, {});
}
```

**Comment by pranjaltech** [comment]
I'm facing the same problem. @jsaleigh any ETA on a solution?

**Comment by jsaleigh** [comment]
Hey all, sorry for not responding to this sooner.  The `forgetHide` option has been updated, and should currently be live.  Hope this helps!
