### ISSUE TITLE
Easylist blocks bnc.lt links

### ISSUE THREAD

**Issue by SleeplessByte** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#239]
Congratulations to making it on the [EasyPrivacy List](https://forums.lanik.us/).

People with Adblock Plus, uBlock (Origin) or similar and EasyPrivacy will never have callbacks come in. 

![image](https://cloud.githubusercontent.com/assets/1964376/11253423/418db872-8df0-11e5-82ed-f1ed67aee226.png)

As soon as it is fingerprinted once, it seem to work (see image).

![screenshot 2015-11-18 12 23 31](https://cloud.githubusercontent.com/assets/1964376/11253248/3cd9edf6-8def-11e5-8339-a2c9d96fb813.png)

Ya'll need fallback domains or detection.

**Comment by derrickstaten** [comment]
@SleeplessByte thanks for the heads up. I've created an account on EasyList and will be marking bnc.lt as improperly blocked.

As for detection, what do you suggest?

**Comment by derrickstaten** [comment]
At the very least we should fail intelligently here -- if bnc.lt is blocked, our SDK should not fail to initialize.

**Comment by SleeplessByte** [comment]
@derrickstaten I would probably implement it as having a 1px image load from something like `bnc.lt/adblock` and see if the element size `1px:1px`

**Comment by aaustin** [comment]
In 1.8.4, we now properly handle the case where we're getting blocked through this mechanism or privacy mode.
