### ISSUE TITLE
Branch setIdentity crash on smartphones

### ISSUE THREAD

**Issue by lwhuybrechts** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#245]
Using branch-sdk: ~1.8.1, installed via bower.

We are noticing crashes on iPhone browser and also on different devices in the Chrome emulator. http://prntscr.com/976k7k

We've been debugging the setIdentity in the branch library in chrome and found that it tries to get the branch_session from the local storage, while it's been stored in the session storage. This results in an empty session.

Looking forward to hearing if anyone else has this bug and if it will be fixed in the near future. Thanks!

**Comment by jsaleigh** [comment]
In the most current version, there are checks for accessibility of various storage methods.  So I believe this has been fixed, but if the latest does work for you, please feel free to reopen.
