### ISSUE TITLE
Add event for clicking the download CTA

### ISSUE THREAD

**Issue by janpaul123** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#255]
There are events for sending an sms (such as didSendBannerSMS), but not for downloading the app on a mobile device. This would be very useful for analytics so we can use funnels in our analytics system. Or is there a specific reason why you didn't add an event for the download CTA?

**Comment by sweetlikepete** [comment]
@janpaul123 I've added a PR with an event called didDeepviewCTA that triggers when download is clicked.

**Comment by jsaleigh** [comment]
This should be available in the current release (v1.8.4).  If you have any issues please let me know :)
