### ISSUE TITLE
Fix testing with saucelabs

### ISSUE THREAD

**Issue by floriangosse** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#276]
All tests of PRs are failed because closing of the tunnel to Sauce Labs.

**Comment by jsaleigh** [comment]
Hey @floriangosse! Thanks for submitting this issue (and the pull request). The reason this is happening is that CircleCI was requiring grunt-cli in peerDependencies within package.json. Previously, this had been kept in devDependencies, and we were seeing the same errors with Sauce Labs that you are seeing now in your pull request.

In the PR, you mentioned "grunt-cli is not needed for the use of the sdk and throws warnings if you try to install it".  Can you describe that more?

**Comment by floriangosse** [comment]
Oh okay. Than there should be added a line in the post dependencies commands which install grunt-cli global with `npm install -g grunt-cli` like the jscs and jshint commands.

Why I make the PR:
I use npm, gulp and browserify for my packaging and bundling. I installed the branch-sdk with npm but it throws the warning that grunt-cli must be installed as peer dependency but itsn't already. But there is no need for grunt in my project setup.

**Comment by floriangosse** [comment]
If look at this test of a PR there is also the connection error like the one which is thrown on the test of my PR: https://circleci.com/gh/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/1615

**Comment by jsaleigh** [comment]
Great advice about the post dependency commands, that does sound much better.  If you want to do a PR with that, I can see about getting it merged in?  Otherwise I'll probably do it soon.

If you do decide to do it, please keep the number of lines changed to a minimum to make git blame easier to use in the future :)

Thanks for all this!

**Comment by floriangosse** [comment]
Okay, I will open a new branch and PR for the global installation solution.

**Comment by floriangosse** [comment]
Okay, my last PR(#278) failed also because of a timeout: https://circleci.com/gh/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/1622

I think there is something wrong with the setup of the saucelab intergration.

**Comment by jsaleigh** [comment]
This is very cool, thank you!  I'll have a look at why Sauce Labs is failing and get this merged in.

More importantly, does this setup work for your development environment?
