### ISSUE TITLE
openAppButtonText don't show the button text in websites.

### ISSUE THREAD

**Issue by Solracollag** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#285]
Hi,

I'm trying the option openAppButtonText: 'OPEN', but the text that appear is the download option instead the one i want.

**Comment by aaustin** [comment]
Hey @Solracollag - It's a bit of magic how we determine whether to show 'Open' versus 'Download' on the smart banner. To explain, once we've seen a user click the banner in mobile web, and set a cookie on the domain, then be redirected into the app with our native SDK in it. We'll save that history in our database. When that user comes back to the site, we'll use the cookie to remember that they previously opened the app and show 'Open' in that case.

Does that help explain why you might be seeing the issue?

**Comment by Solracollag** [comment]
Ok, tx @aaustin  for your explanation, now i feel a little dumb after hearing it.
