### ISSUE TITLE
Deepview launches "open in app store" prompt when user has the app

### ISSUE THREAD

**Issue by jamesfzhang** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#315]
I added a deepview for mobile web to launch the app or direct the user to the App Store. I noticed that even when I have the app, the browser is prompting me to open the app in the App Store. I expect it to open the app directly.

**Comment by jsaleigh** [comment]
Hey @jamesfzhang , sorry that you ran into that issue.  We're actively working on a fix, and it is in review right now.

If you want to have a look at the current status of it, the PR is https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/pull/313

I'll be sure to ping you on this issue when we know we have a solve.

**Comment by jsaleigh** [comment]
@jamesfzhang we have a fix in place and live in the latest build, that has been out for a bit now.  From what we've seen, this is handling the majority of the cases for determining whether a user has an app installed.
