### ISSUE TITLE
TypeError: object does not support the 'remove' property or method .

### ISSUE THREAD

**Issue by jamesfzhang** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#319]
This error occurs for users on IE11. I see variations from all different languages. The trace points to `
File https://cdn.branch.io/branch-latest.min.js line 27 col 492 in Anonymous function`.

**Comment by jsaleigh** [comment]
@jamesfzhang Thanks for the head's up...it appears that this is happening during an attempt to cleanup script tags created during jsonp requests.  We'll get a fix out as soon as possible for it.

**Comment by jamesfzhang** [comment]
Thanks John, appreciate it.

**Comment by jsaleigh** [comment]
@jamesfzhang We've deployed a new Web SDK version to fix this, v2.1.5.  Once the cache clears on `https://cdn.branch.io/branch-latest.min.js`, the build should be available there.

Thanks again for finding this! 😄
