### ISSUE TITLE
Smart Banner doesn't show up if "Do not track" setting in browser is turned on

### ISSUE THREAD

**Issue by h15ter** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#322]
Hi Guys,

I understand why it happens, I see the code in banner_utils.shouldAppend and I have read the corresponding statement at your privacy policy update page (https://branch.io/privacy_policy/).

The problem is that I can't override it without source code modification.

We don’t want our users to miss great features of the app just because of some in-browser setting people often are not aware of. It's an absolute stopper for us.

There should be a config setting to either respect or ignore 'doNotTrack' header.

Are you willing to fix it or accept pull request with the fix?

**Comment by aaustin** [comment]
Hey @h15ter - We'd be willing to do both! We're a bit swamped at the moment, so if it's urgent, it'd be better to roll the fix yourself and let us approve.

Sorry about the confusion here. We had a few requests to do a better job respecting doNotTrack in the browser.

Let me know what you decide.

**Comment by h15ter** [comment]
Hi @aaustin 
I've created a pull request with a very simple fix. Please take a look.

Btw it wasn't a trivial task to build the project from sources. If you want more people to contribute the project, it might be a good idea to write some sort of how-to :)

Here is the list of major issues I've experienced:
1) Latest Google Closure Compiler failed to compile the code from master. I had to use some older version of compiler. At the same time makefile references the latest one by default, which is pretty confusing.
2) Path of the Lint script used by pre-commit git hook is in linux format, which prevents code from being committed on windows.
3) Makefile has some issues (like usage of global jsdox instead of the one from node_modules), and you need to be pretty motivated to go though all the challenges to build the code :)
4) Missing tests/placeholders for some modules, which means that contributor making a small code change can't easily add a few tests to cover the change.

**Comment by jsaleigh** [comment]
@h15ter awesome, thanks!  I'll get this merge in and deployed today.

**Comment by jsaleigh** [comment]
This has been deployed as version 2.1.6.  Thanks again @h15ter!

Also thanks for the notes on updating the build process, and adding docs.  We have been cleaning up the code recently, but there are still a few points we need to hit.
