### ISSUE TITLE
Fix AMD compatibility

### ISSUE THREAD

**Issue by Thinkscape** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#66]
Well, #2 isn't resolved and it seems that v2 branch is dead.
The script still isn't very AMD friendly, even though it's just a few lines to make it so :-)

You could use something well-tested such as https://github.com/umdjs/umd

**Comment by dmitrig01** [comment]
Hrmm, I thought we tested it with AMD - we are using UMD.

@scotthasbrouck can you take a look?

**Comment by scotthasbrouck** [comment]
Will do!

**Comment by scotthasbrouck** [comment]
Hi @Thinkscape Could you clarify what specific issues you're seeing with AMD. It seems to work on my end so I want to make sure I address completely address this.

**Comment by Thinkscape** [comment]
Keep it open for now. I can't debug this ATM so I've halted lib upgrade for now. Will get to it soon.

**Comment by aaustin** [comment]
@Thinkscape did you have a chance to check into this?

**Comment by tjanela** [comment]
Hum, from what I can see, using RequireJS I use this line:
```javascript
define(['angular', 'branch-sdk'], function (angular, branchSdk){
    'use strict';
    //Rest of code
});
```
However, branchSdk variable is null. Also the global namespace contains branch as well as window.branch

Let me know how can I help you guys sort this.

**Comment by tjanela** [comment]
I dug some more into this issue and it seems that having a module with name 'branch-sdk' will make bower-requirejs write:
```javascript
require.config({
  paths: {
    //other stuff
    'branch-sdk': '../../bower_components/branch-sdk/dist/build.min'
  }
 // other stuff
});
```
This leads us to write what I posted in my previous comment resulting in unexpected behaviour.

**Comment by jsaleigh** [comment]
Hey all, we've done a fair amount of reorganization with the code, and have made some changes in this area over the past few months.  From what I see this is working, closing out for now, but if you run into issues again we can open it back up.  Thanks! :)
