### ISSUE TITLE
$after_click_url breaks detection of user having app

### ISSUE THREAD

**Issue by emilycoco** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#67]
If you set $after_click_url, the data passed in init (or shown in the banner) can no longer detect that the user has the app, will always default to data.has_app = false;
has_app is not set in sessionStorage before redirecting.

**Comment by Kirkkt** [comment]
Quick update: 

We are waiting for 
https://github.com/BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK/pull/89 
to be merged. Shouldn't take more than a couple of days. We discovered a very similar issue in the process of working on this PR, and this PR contains a fix to that.

Stay tuned!
