### ISSUE TITLE
Cordova plugin - handleOpenUrl is never called

### ISSUE THREAD

**Issue by wedgybo** [BranchMetrics/Smart-App-Banner-Deep-Linking-Web-SDK#78]
I'm having a lot of consistency problems with the cordova integration. It looks like BNCDevice.m pretty much does nothing from a standard install using 

cordova plugin add https://github.com/BranchMetrics/Web-SDK.git

The handleOpenURL function is never called because the plugin is never told to listen for the handleOpen notification

The getOpenData seems redundant also. I can see some calls to it inside the build.js file supplied with the plugin, but the breakpoint in either getInstallData or getOpenData is never hit. Again this is in minified code so it's tricky to see what's going on but I'll start digging deeper to see why.

I guess what I'd like to know is are these things meant to be called. Or is the plugin actually redundant now and it should all work from the WebSDK? I'm getting a bit confused and I don't want to waste time going down the wrong path.

Any advice would be appreciated!

**Comment by aaustin** [comment]
Hey @wedgybo - this is a pretty atrocious list of faults that we can dig into right away. I'm pretty sure you don't need to use handleOpenURL, as all you need to do is to execute this code once the ‘deviceready’ event fires and each time the ‘resume’ event fires

  branch.init("YOUR BRANCH KEY HERE", function(err, data) {
    app.initComplete(err, data);
  });

You need to use the Cordova version instead of the Web SDK version because it does execute some device specific code, but the methods are the same as the Cordova library.

It seems like you're on the right path!

**Comment by wedgybo** [comment]
Ok. I'm calling the branch.init function on both of those events. Here's my test code.

```
function initBranch() {
    console.log('BRANCH INIT');
    branch.init(BRANCH_KEY, { isReferrable: true }, function (err, data) {
      console.log('BRANCH DATA', err, data);
    });
}

document.addEventListener('deviceready', initBranch, false);
document.addEventListener('resume', initBranch, false);
```

Now I see BRANCH INIT and  BRANCH DATA on my cold start no problem, from a warm start it only runs BRANCH INIT.

The problem appears to lie somewhere here. https://github.com/BranchMetrics/Web-SDK/blob/master/src/3_branch.js#L306

The SDK know's there's a session so it fires on with the web flow. Unfortunately it doesn't have the information from the click so the data object is never updated and always returns the first data object found.

Looking through the code, I expect it to get here https://github.com/BranchMetrics/Web-SDK/blob/master/src/3_branch.js#L319 and pull the information stored natively from processing the handleOpenUrl request.

I think the condition never being hit in my case because it looks like the close function isn't doing what it's meant to in this instance.

I'll have another play again to see what's going on if you think I'm on the right path?

**Comment by scotthasbrouck** [comment]
hey @wedgybo great catch with this. I stepped through this and can confirm that line 306 is, in fact, the issue. I've added  afurther conditional to only init the Web SDK on the following line if it is the web environment (if WEB_BUILD) is true, so now, the init function on Cordova continues on, calls open, and loads the new data object. I'm going to open a PR for this - which you're welcome to pull down and give a run before we release the fix. Feel free to send any other problems you're having with this and I'll be happy to get quick fixes out!

**Comment by aaustin** [comment]
@wedgybo Can you confirm that the latest version https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK did in fact resolve this?

**Comment by wedgybo** [comment]
I've not been back on to it recently due to other commitments. It wasn't working last I checked but I noticed there's been quite a few commits since then. I will try to find time to test it this week again.

**Comment by Kirkkt** [comment]
@wedgybo 

I'm going through all open issues. Did you have a chance to test whether the latest Cordova SDK works for you?

**Comment by wedgybo** [comment]
Going back to this today. So I'll let you know!

**Comment by aaustin** [comment]
Hi @wedgybo - we've migrated the Cordova/Ionic SDK to a separate repository: https://github.com/BranchMetrics/Cordova-Ionic-PhoneGap-Deferred-Deep-Linking-SDK and: https://www.npmjs.com/package/branch-cordova-sdk This should be resolved.
